apiVersion: v1
kind: PersistentVolume
metadata:
  name: vbook-mysql-pvc
spec:
  storageClassName: record
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"